version: "3"

networks:
  dda:
    external:
      name: dda

services:
  odoo-db:
    container_name: odoo-db
    image: postgres:10
    environment:
      - "POSTGRES_USER=odoo"
      - "POSTGRES_PASSWORD=odoo"
      - "POSTGRES_DB=postgres"
    networks:
      - dda

  odoo-service:
    container_name: odoo-service
    image: odoo:latest
    external_links:
      - odoo-db:db
    ports:
      - 8069:8069
    networks:
      - dda
    volumes:
      - ./add_ons:/mnt/extra-addons