version: "3"

networks:
  dda:
    external:
      name: dda

services:
  odoo-db:
    container_name: odoo-db
    image: postgres:10
    environment:
      - "POSTGRES_USER=odoo"
      - "POSTGRES_PASSWORD=odoo"
      - "POSTGRES_DB=postgres"
    networks:
      - dda